#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

if (! extension_loaded('pdo_mysql') && ! getenv('PHP_INI_RETRY') && function_exists('pcntl_exec')) {
    putenv('PHP_INI_RETRY=1');
    putenv('PHP_INI_SCAN_DIR=:/home/rafidan/.config/php');
    pcntl_exec(PHP_BINARY, $_SERVER['argv']);
}

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
